name: tests
env:
  MAVEN_OPTS: -Dmaven.resolver.transport=native -Daether.connector.connectTimeout=300000
    -Daether.connector.requestTimeout=300000
  NIX_OPTIONS: --ignore-environment --keep MAVEN_OPTS --keep PATH --keep LANG
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
jobs:
  test-linux:
    runs-on: self-hosted
    name: Tests with Java ${{ matrix.java }} on ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - java: '17'
          os: ubuntu-latest
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop .#jdk${{ matrix.java }} ${{ env.NIX_OPTIONS }} --command true
    - name: Test
      run: nix develop .#jdk${{ matrix.java }} ${{ env.NIX_OPTIONS }} --command test
    timeout-minutes: 6
  coverage:
    runs-on: self-hosted
    name: Test with coverage
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - name: Run tests with coverage
      run: nix develop ${{ env.NIX_OPTIONS }} --keep PR_NUMBER --keep GITHUB_TOKEN
        --command coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
    timeout-minutes: 6
  extra:
    runs-on: self-hosted
    name: Extra checks
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command true
    - name: Run extra checks
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command extra
    - name: Trigger extra remote tasks
      if: true && github.event_name == 'pull_request'
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command extra-remote
    timeout-minutes: 6
  javadoc:
    runs-on: self-hosted
    name: Javadoc quality
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command true
    - name: Build spoon
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command mvn -f spoon-pom
        -B install -Dmaven.test.skip=true
    - name: Run Javadoc quality check
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command javadoc-quality
    timeout-minutes: 6
  reproducible-builds:
    runs-on: self-hosted
    name: reproducible-builds
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - name: Check status
      run: nix develop ${{ env.NIX_OPTIONS }} --command reproducible-builds
    timeout-minutes: 6
  maven-central-requirements:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - name: Check maven pom quality
      run: nix develop ${{ env.NIX_OPTIONS }} --command maven-pom-quality
    timeout-minutes: 6
  codegen:
    runs-on: self-hosted
    name: Codegeneration
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Setup env
      uses: ./.github/actions/setup-tests
    - name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - name: Run codegen checks
      run: nix develop ${{ env.NIX_OPTIONS }}  --command codegen
    timeout-minutes: 6
'on':
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - chore/flakey-flakey-rise-and-shine
  schedule:
  - cron: 0 0 * * *
